// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizManagement.Infrastructure.Persistence;

#nullable disable

namespace QuizManagement.Infrastructure.Migrations
{
    [DbContext(typeof(QuizManagementDbContext))]
    partial class QuizManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizManagement.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", "quiz");
                });

            modelBuilder.Entity("QuizManagement.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("Questions", "quiz");
                });

            modelBuilder.Entity("QuizManagement.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions", "quiz");
                });

            modelBuilder.Entity("QuizManagement.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Quizzes", "quiz");
                });

            modelBuilder.Entity("QuizManagement.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags", "quiz");
                });

            modelBuilder.Entity("QuizManagement.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("QuizManagement.Domain.Entities.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizManagement.Domain.Entities.Quiz", b =>
                {
                    b.OwnsOne("QuizManagement.Domain.Entities.ExamConfig", "ExamConfig", b1 =>
                        {
                            b1.Property<Guid>("QuizId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double?>("PassingScore")
                                .HasColumnType("float")
                                .HasColumnName("PassingScore");

                            b1.Property<double>("PointsCorrect")
                                .HasColumnType("float")
                                .HasColumnName("PointsCorrect");

                            b1.Property<double>("PointsSkipped")
                                .HasColumnType("float")
                                .HasColumnName("PointsSkipped");

                            b1.Property<double>("PointsWrong")
                                .HasColumnType("float")
                                .HasColumnName("PointsWrong");

                            b1.Property<bool>("ShuffleOptions")
                                .HasColumnType("bit")
                                .HasColumnName("ShuffleOptions");

                            b1.Property<bool>("ShuffleQuestions")
                                .HasColumnType("bit")
                                .HasColumnName("ShuffleQuestions");

                            b1.Property<int>("TimeLimitSeconds")
                                .HasColumnType("int")
                                .HasColumnName("TimeLimitSeconds");

                            b1.HasKey("QuizId");

                            b1.ToTable("Quizzes", "quiz");

                            b1.WithOwner()
                                .HasForeignKey("QuizId");
                        });

                    b.OwnsMany("QuizManagement.Domain.Entities.QuizQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("QuizId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("OrderIndex")
                                .HasColumnType("int");

                            b1.HasKey("QuizId", "QuestionId");

                            b1.ToTable("QuizQuestions", "quiz");

                            b1.WithOwner()
                                .HasForeignKey("QuizId");
                        });

                    b.Navigation("ExamConfig")
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizManagement.Domain.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
