// <auto-generated />
using System;
using ExamEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamEngine.Infrastructure.Migrations
{
    [DbContext(typeof(ExamEngineDbContext))]
    [Migration("20260515195840_AddConfigSnapshotAnalyticsFields")]
    partial class AddConfigSnapshotAnalyticsFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamEngine.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("NormalizedScore")
                        .HasColumnType("float");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExamSessions", "exam");
                });

            modelBuilder.Entity("ExamEngine.Domain.Entities.SessionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double>("PointsAwarded")
                        .HasColumnType("float");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SelectedOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionAnswers", "exam");
                });

            modelBuilder.Entity("ExamEngine.Domain.Entities.ExamSession", b =>
                {
                    b.OwnsOne("ExamEngine.Domain.Entities.ConfigSnapshot", "Config", b1 =>
                        {
                            b1.Property<Guid>("ExamSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("CategoryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CategoryId");

                            b1.Property<double?>("PassingScore")
                                .HasColumnType("float")
                                .HasColumnName("PassingScore");

                            b1.Property<double>("PointsCorrect")
                                .HasColumnType("float")
                                .HasColumnName("PointsCorrect");

                            b1.Property<double>("PointsSkipped")
                                .HasColumnType("float")
                                .HasColumnName("PointsSkipped");

                            b1.Property<double>("PointsWrong")
                                .HasColumnType("float")
                                .HasColumnName("PointsWrong");

                            b1.Property<string>("QuizTitle")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("QuizTitle");

                            b1.Property<bool>("ShuffleOptions")
                                .HasColumnType("bit")
                                .HasColumnName("ShuffleOptions");

                            b1.Property<bool>("ShuffleQuestions")
                                .HasColumnType("bit")
                                .HasColumnName("ShuffleQuestions");

                            b1.Property<int>("TimeLimitSeconds")
                                .HasColumnType("int")
                                .HasColumnName("TimeLimitSeconds");

                            b1.HasKey("ExamSessionId");

                            b1.ToTable("ExamSessions", "exam");

                            b1.WithOwner()
                                .HasForeignKey("ExamSessionId");
                        });

                    b.Navigation("Config")
                        .IsRequired();
                });

            modelBuilder.Entity("ExamEngine.Domain.Entities.SessionAnswer", b =>
                {
                    b.HasOne("ExamEngine.Domain.Entities.ExamSession", null)
                        .WithMany("Answers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamEngine.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
